DROP DATABASE IF EXISTS starrail;

CREATE DATABASE IF NOT EXISTS starrail;
USE starrail;

CREATE TABLE IF NOT EXISTS news_type (
  id INT NOT NULL AUTO_INCREMENT,
  news_type VARCHAR(16) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE UNIQUE INDEX idx_fk_news_type
ON news_type (news_type);

CREATE TABLE IF NOT EXISTS locale (
  id INT NOT NULL AUTO_INCREMENT,
  locale VARCHAR(16) NOT NULL,
  language VARCHAR(16) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE UNIQUE INDEX idx_fk_locale
ON locale (locale);

CREATE TABLE IF NOT EXISTS news (
  id INT NOT NULL AUTO_INCREMENT,
  news_id INT NOT NULL,
  locale VARCHAR(16) NOT NULL,
  news_type VARCHAR(16) NOT NULL,
  title VARCHAR(512) NOT NULL,
  intro VARCHAR(512) NOT NULL,
  image VARCHAR(512) NOT NULL,
  content LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (news_type) REFERENCES news_type (news_type),
  FOREIGN KEY (locale) REFERENCES locale (locale),
  CONSTRAINT UQ_Newsid_Locale UNIQUE(news_id, locale)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE INDEX idx_news_id
ON news (news_id);

CREATE INDEX idx_news_type
ON news (news_type);

CREATE INDEX idx_locale
ON news (locale);

CREATE TABLE IF NOT EXISTS register_user (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  verification_code VARCHAR(16),
  verified BOOLEAN NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT UQ_Email UNIQUE (email)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS user (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  session_id VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT UQ_Email UNIQUE (email),
  CONSTRAINT UQ_Username UNIQUE (username)
 ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;